### ISSUE TITLE
[admin] connexion/écran principal

### ISSUE THREAD

**Issue by kevinonce** [abdelrhamaneben/EasyTrip-api#27]
corriger les problèmes à la connexion et à l'affichage de l'écran principal ( supprimer le besoin de rafraichir)

**Comment by jvdurieu** [comment]
C'est réglé !
Description : 
Pour une raison inconnue, dans le controlleur login de l'app client, il ne résoud pas "$state.go('user.home');". Je l'ai donc changé en "$state.go('admin.homebu');" et j'ai associé les modifications dans app.js pour les routes. Et la ca fonctionne bien. Pour corriger le problème plus correctement il faudrait se pencher sur la hiérarchie des routes dans app.js
