### ISSUE TITLE
[front] fix video firefox

### ISSUE THREAD

**Issue by kevinonce** [abdelrhamaneben/EasyTrip-api#46]

**Comment by abdelrhamaneben** [comment]
Proposition de video de font (Mix de video possible) : 
https://www.youtube.com/watch?v=he9dNNfOLHo
https://www.youtube.com/watch?v=XU53fN16wc8 (^^)
https://www.youtube.com/watch?v=AQ6GmpMu5L8
https://www.youtube.com/watch?v=DEJx0CYrDHk
https://www.youtube.com/watch?v=ieWNzZPfZzk

**Comment by jvdurieu** [comment]
Desireless direct ! :D
Sinon j'aime bien celle de Rio de Janeiro. Ce qui serait trooop al claaaas, c'est de faire comme eux une mini intro (un encart avec le nom du site), et alors mettre un timer d'une seconde avant d'afficher le DIV qui contient le logo et le chammp de recherche. Et si c'est bien fait ca fait un super fade in de malade, richard il va kiffer ! :)

**Comment by abdelrhamaneben** [comment]
la video choisie est  _Hello_  Adele
