### ISSUE TITLE
[admin] fix du login - logout

### ISSUE THREAD

**Issue by kevinonce** [abdelrhamaneben/EasyTrip-api#56]
La déconnexion ne fonctionne pas

**Comment by sahraoui62** [comment]
Stocker l'user dans le $rootScope lors de la connexion ne fonctionne pas dans tous les cas, car le $rootScope perd les infos quand on recharge la page.
J'ai testé les variables de sessions et les cookies mais sans succès, il y a quelque chose qui m'échappe certainement....
**JV** peut tu rééssayer de corriger le problème stp ?

**Comment by Najtal** [comment]
Une solution pas propre et pas sécurisée c'est de l'enregistrer dans le navigateur.
http://html5doctor.com/storing-data-the-simple-html5-way-and-a-few-tricks-you-might-not-have-known/
Je regarde ca tantôt.

**Comment by sahraoui62** [comment]
Ok pour le Logout + login. Reste juste a voir pourquoi quand on se log avec un compte business, on accede pas a la page suivante.
