### ISSUE TITLE
[ADMIN] Fix signup

### ISSUE THREAD

**Issue by sahraoui62** [abdelrhamaneben/EasyTrip-api#61]
Impossible de créer un compte dû a des modifications que tu as faites JV, je te laisse gérer ca pour pas tout casser la logique que tu avais

**Comment by Najtal** [comment]
Done !
Par contre il n'y a pas de tests celenium sur cette partie.

**Comment by sahraoui62** [comment]
Je pense que tu as commit mais tu as peut être oublié de push ^^
Peut tu push sur dev stp, j'ai besoin du signup pour finir mes tests pour la présentation.
J'ai cherché sur toutes les branches, je ne trouve pas
